#!/bin/python3
import os
import sys
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from statannot import add_stat_annotation
# python3 plot_filtered_SNV_count_manuscript.py filtered_SNV_count_manuscript_Ti_subsampled.txt (generated by for BARCODE_ID in ${BARCODE_LIST[@]}; do echo $BARCODE_ID; zgrep -c -v "^#" $BARCODE_ID.vcf.gz; done)

mh_df = pd.read_csv(sys.argv[1], sep="\t", names=['sample', 'count', 'category'])
my_order = ['amplified', 'unamplified']

fig, axes = plt.subplots(1, 1, figsize=(7, 5))
sns.boxplot(x="category", y="count", data=mh_df, ax=axes, order=my_order)
sns.swarmplot(x="category", y="count", data=mh_df, color="black", size=3, ax=axes, order=my_order)
axes.set_ylabel("Count", fontsize=16)
axes.set_xlabel("Category", fontsize=16)
axes.set_title("Somatic SNV count in ES", fontsize=16)
add_stat_annotation(axes, data=mh_df, x="category", y="count",
                    box_pairs=[("amplified", "unamplified")],
                    test='Mann-Whitney', text_format='full', loc='inside', verbose=2)
plt.savefig("WES_filered_SNV_count_manuscript_Ti_subsampled.pdf")